services:
  - type: web
    name: asin-regulations
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python app/db.py && python app/load_data.py && python pipeline/load_revision_history.py"
    startCommand: "uvicorn main:app --app-dir app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
